drop table if exists Categoria;
drop table if exists hibernate_sequence;
drop table if exists Palavra;
drop table if exists palavra_categoria;
create table Categoria (categoria_id integer not null, categoria_descricao varchar(255), primary key (categoria_id));
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Palavra (id integer not null, descricao varchar(255), tamanho integer, primary key (id));
create table palavra_categoria (palavra_id integer not null, categoria_id integer not null, primary key (palavra_id, categoria_id));
alter table palavra_categoria add constraint FKfcp1u8ya2hs9vqdasi2vqm6tx foreign key (categoria_id) references Categoria (categoria_id);
alter table palavra_categoria add constraint FK5c4ak9vh6gsnk6223ur3oxm30 foreign key (palavra_id) references Palavra (id);
drop table if exists entities.palavra;
drop table if exists entities.categoria;
drop table if exists palavra_categoria;
create table entities.palavra (palavra_id integer not null auto_increment, descricao varchar(20) not null, tamanho integer, primary key (palavra_id));
create table categoria (categoria_id integer not null auto_increment, categoria_descricao varchar(10) not null, primary key (categoria_id));
create table palavra_categoria (palavra_id integer not null, categoria_id integer not null, primary key (palavra_id, categoria_id));
alter table palavra_categoria add constraint FKfs36ahqu17bv2mdnarcbyifnp foreign key (categoria_id) references categoria (categoria_id);
alter table palavra_categoria add constraint FKm62v0llk3upk2vmrxan2dxjpk foreign key (palavra_id) references entities.palavra (palavra_id);
drop table if exists entities.categoria;
drop table if exists entitiesPalavra;
drop table if exists palavra_categoria;
create table categoria (categoria_id integer not null auto_increment, categoria_descricao varchar(10) not null, primary key (categoria_id));
create table Palavra (palavra_id integer not null auto_increment, descricao varchar(20) not null, tamanho integer, primary key (palavra_id));
create table palavra_categoria (palavra_id integer not null, categoria_id integer not null, primary key (palavra_id, categoria_id));
alter table palavra_categoria add constraint FKfs36ahqu17bv2mdnarcbyifnp foreign key (categoria_id) references categoria (categoria_id);
alter table palavra_categoria add constraint FK5c4ak9vh6gsnk6223ur3oxm30 foreign key (palavra_id) references Palavra (palavra_id);
drop table if exists categoria;
drop table if exists hibernate_sequence;
drop table if exists Palavra;
drop table if exists palavra_categoria;
create table categoria (categoria_id integer not null, categoria_descricao varchar(10) not null, primary key (categoria_id));
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Palavra (palavra_id integer not null, descricao varchar(20) not null, tamanho integer, primary key (palavra_id));
create table palavra_categoria (palavra_id integer not null, categoria_id integer not null, primary key (palavra_id, categoria_id));
alter table palavra_categoria add constraint FKfs36ahqu17bv2mdnarcbyifnp foreign key (categoria_id) references categoria (categoria_id);
alter table palavra_categoria add constraint FK5c4ak9vh6gsnk6223ur3oxm30 foreign key (palavra_id) references Palavra (palavra_id);
drop table if exists Categoria;
drop table if exists hibernate_sequence;
drop table if exists Palavra;
drop table if exists palavra_categoria;
create table Categoria (categoria_id integer not null, categoria_descricao varchar(255), primary key (categoria_id));
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Palavra (palavra_id integer not null, descricao varchar(255), tamanho integer, primary key (palavra_id));
create table palavra_categoria (palavra_id integer not null, categoria_id integer not null, primary key (palavra_id, categoria_id));
alter table palavra_categoria add constraint FKfcp1u8ya2hs9vqdasi2vqm6tx foreign key (categoria_id) references Categoria (categoria_id);
alter table palavra_categoria add constraint FK5c4ak9vh6gsnk6223ur3oxm30 foreign key (palavra_id) references Palavra (palavra_id);
drop table if exists Categoria;
drop table if exists hibernate_sequence;
drop table if exists Palavra;
drop table if exists palavra_categoria;
create table Categoria (categoria_id integer not null, categoria_descricao varchar(255), primary key (categoria_id));
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Palavra (palavra_id integer not null, descricao varchar(255), tamanho integer, primary key (palavra_id));
create table palavra_categoria (palavra_id integer not null, categoria_id integer not null, primary key (palavra_id, categoria_id));
alter table palavra_categoria add constraint FKfcp1u8ya2hs9vqdasi2vqm6tx foreign key (categoria_id) references Categoria (categoria_id);
alter table palavra_categoria add constraint FK5c4ak9vh6gsnk6223ur3oxm30 foreign key (palavra_id) references Palavra (palavra_id);
drop table if exists Categoria;
drop table if exists hibernate_sequence;
drop table if exists Palavra;
drop table if exists palavra_categoria;
create table Categoria (categoria_id integer not null, categoria_descricao varchar(255), primary key (categoria_id));
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Palavra (palavra_id integer not null, descricao varchar(255), tamanho integer, primary key (palavra_id));
create table palavra_categoria (palavra_id integer not null, categoria_id integer not null, primary key (palavra_id, categoria_id));
alter table palavra_categoria add constraint FKfcp1u8ya2hs9vqdasi2vqm6tx foreign key (categoria_id) references Categoria (categoria_id);
alter table palavra_categoria add constraint FK5c4ak9vh6gsnk6223ur3oxm30 foreign key (palavra_id) references Palavra (palavra_id);
drop table if exists Categoria;
drop table if exists hibernate_sequence;
drop table if exists Palavra;
drop table if exists palavra_categoria;
create table Categoria (categoria_id integer not null, categoria_descricao varchar(255), primary key (categoria_id));
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Palavra (id integer not null, descricao varchar(255), tamanho integer, primary key (id));
create table palavra_categoria (palavra_id integer not null, categoria_id integer not null, primary key (palavra_id, categoria_id))
alter table palavra_categoria add constraint FKfcp1u8ya2hs9vqdasi2vqm6tx foreign key (categoria_id) references Categoria (categoria_id);
alter table palavra_categoria add constraint FK5c4ak9vh6gsnk6223ur3oxm30 foreign key (palavra_id) references Palavra (id);
drop table if exists CATEGORIA;
drop table if exists hibernate_sequence;
drop table if exists PALAVRA;
drop table if exists PALAVRA_CATEGORIA;
create table CATEGORIA (CATEGORIA_ID integer not null, CATEGORIA_DESCRICAO varchar(255), primary key (CATEGORIA_ID)) type=MyISAM;
create table hibernate_sequence (next_val bigint) type=MyISAM;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table PALAVRA (PALAVRA_ID integer not null, PALAVRA_DESCRICAO varchar(100) not null, tamanho integer, primary key (PALAVRA_ID)) type=MyISAM;
create table PALAVRA_CATEGORIA (PALAVRA_ID integer not null, CATEGORIA_ID integer not null, primary key (PALAVRA_ID, CATEGORIA_ID)) type=MyISAM;
alter table PALAVRA_CATEGORIA add constraint FKxcm0fnyjjjon840jrqoowc7g foreign key (CATEGORIA_ID) references CATEGORIA (CATEGORIA_ID);
alter table PALAVRA_CATEGORIA add constraint FKkxopj7w56l51673ogpea3uel3 foreign key (PALAVRA_ID) references PALAVRA (PALAVRA_ID);
drop table if exists CATEGORIA;
drop table if exists PALAVRA;
create table CATEGORIA (CATEGORIA_ID integer not null, CATEGORIA_DESCRICAO varchar(255), primary key (CATEGORIA_ID)) type=MyISAM;
create table PALAVRA (PALAVRA_ID integer not null, PALAVRA_DESCRICAO varchar(255), primary key (PALAVRA_ID)) type=MyISAM;
